// data8.js

import { unknown } from "zod";

export const rows = [
  {
    key: 1,
    orderNumber: 'ORD001',
    TrackNumber: 'TRK001',
    statut: 'Confirmed',
    date: '2023-10-01',
    name: 'John Doe',
    price: '$100',
    shipping: 'Standard',
    products: 'Product A, Product B',
    from: 'Warehouse A',
    to: 'Customer Address',
    city: 'City A',
    address: '123 Main St',
    shipby: 'DHL',
    status: 'archived',
    unknown: 'BBBBBBBB',
    unknown2: 'BBBBBBBB'
  },
  {
    key: 2,
    orderNumber: 'ORD002',
    TrackNumber: 'TRK002',
    statut: 'Shipped',
    date: '2023-10-02',
    name: 'Jane Smith',
    price: '$150',
    shipping: 'Express',
    products: 'Product C',
    from: 'Warehouse B',
    to: 'Customer Address',
    city: 'City B',
    address: '456 Elm St',
    shipby: 'FedEx',
    status: 'archived',
        unknown: 'BBBBBBBB',
    unknown2: 'BBBBBBBB'
  },
  {
    key: 3,
    orderNumber: 'ORD003',
    TrackNumber: 'TRK003',
    statut: 'Pending',
    date: '2023-10-03',
    name: 'Alice Johnson',
    price: '$200',
    shipping: 'Overnight',
    products: 'Product D, Product E',
    from: 'Warehouse C',
    to: 'Customer Address',
    city: 'City C',
    address: '789 Pine St',
    shipby: 'UPS',
    status: 'archived',
        unknown: 'BBBBBBBB',
    unknown2: 'BBBBBBBB'
  },
  {
    key: 4,
    orderNumber: 'ORD004',
    TrackNumber: 'TRK004',
    statut: 'Delivered',
    date: '2023-10-04',
    name: 'Bob Williams',
    price: '$250',
    shipping: 'Standard',
    products: 'Product F',
    from: 'Warehouse D',
    to: 'Customer Address',
    city: 'City D',
    address: '321 Oak St',
    shipby: 'USPS',
    status: 'archived',
        unknown: 'BBBBBBBB',
    unknown2: 'BBBBBBBB'
  },
  {
    key: 5,
    orderNumber: 'ORD005',
    TrackNumber: 'TRK005',
    statut: 'Confirmed',
    date: '2023-10-05',
    name: 'Charlie Brown',
    price: '$300',
    shipping: 'Standard',
    products: 'Product G',
    from: 'Warehouse E',
    to: 'Customer Address',
    city: 'City E',
    address: '654 Maple Ave',
    shipby: 'DHL',
    status: 'archived',
        unknown: 'BBBBBBBB',
    unknown2: 'BBBBBBBB'
  },

  {
    key: 6,
    orderNumber: 'ORD006',
    TrackNumber: 'TRK006',
    statut: 'Shipped',
    date: '2023-10-06',
    name: 'Diana Prince',
    price: '$350',
    shipping: 'Express',
    products: 'Product H',
    from: 'Warehouse F',
    to: 'Customer Address',
    city: 'City F',
    address: '987 Birch Rd',
    shipby: 'FedEx',
    status: 'archived',
        unknown: 'BBBBBBBB',
    unknown2: 'BBBBBBBB'
  },
  {
    key: 7,
    orderNumber: 'ORD007',
    TrackNumber: 'TRK007',
    statut: 'Pending',
    date: '2023-10-07',
    name: 'Ethan Hunt',
    price: '$400',
    shipping: 'Overnight',
    products: 'Product I, Product J',
    from: 'Warehouse G',
    to: 'Customer Address',
    city: 'City G',
    address: '159 Cedar Blvd',
    shipby: 'UPS',
    status: 'archived',
        unknown: 'BBBBBBBB',
    unknown2: 'BBBBBBBB'
  },
  {
    key: 8,
    orderNumber: 'ORD008',
    TrackNumber: 'TRK008',
    statut: 'Delivered',
    date: '2023-10-08',
    name: 'Fiona Gallagher',
    price: '$450',
    shipping: 'Standard',
    products: 'Product K',
    from: 'Warehouse H',
    to: 'Customer Address',
    city: 'City H',
    address: '753 Walnut St',
    shipby: 'USPS',
    status: 'archived',
        unknown: 'BBBBBBBB',
    unknown2: 'BBBBBBBB'
  },
  {
    key: 9,
    orderNumber: 'ORD009',
    TrackNumber: 'TRK009',
    statut: 'Confirmed',
    date: '2023-10-09',
    name: 'George Lucas',
    price: '$500',
    shipping: 'Standard',
    products: 'Product L',
    from: 'Warehouse I',
    to: 'Customer Address',
    city: 'City I',
    address: '357 Spruce Ln',
    shipby: 'DHL',
    status: 'archived',
        unknown: 'BBBBBBBB',
    unknown2: 'BBBBBBBB'
  },
  {
    key: 10,
    orderNumber: 'ORD010',
    TrackNumber: 'TRK010',
    statut: 'Shipped',
    date: '2023-10-10',
    name: 'Hannah Montana',
    price: '$550',
    shipping: 'Express',
    products: 'Product M',
    from: 'Warehouse J',
    to: 'Customer Address',
    city: 'City J',
    address: '246 Oakwood Dr',
    shipby: 'FedEx',
        unknown: 'BBBBBBBB',
    unknown2: 'BBBBBBBB'
  },
  // You can add more entries as needed, ensuring all have 'status': 'archived'
];
