export const rows = [
    {
      key: "1",
      title: "Template 1",
      alias: "Template A",
      type: "Type 1",
      statut: "Enabled",
      account: "Account 1",
    },
    {
      key: "2",
      title: "Template 2",
      alias: "Template B",
      type: "Type 2",
      statut: "Disabled",
      account: "Account 2",
    },
    {
      key: "3",
      title: "Template 3",
      alias: "Template C",
      type: "Type 3",
      statut: "Enabled",
      account: "Account 3",
    },
    {
      key: "4",
      title: "Template 4",
      alias: "Template D",
      type: "Type 4",
      statut: "Disabled",
      account: "Account 4",
    },
    {
      key: "5",
      title: "Template 5",
      alias: "Template E",
      type: "Type 5",
      statut: "Enabled",
      account: "Account 5",
    },
    {
      key: "6",
      title: "Template 6",
      alias: "Template F",
      type: "Type 6",
      statut: "Enabled",
      account: "Account 6",
    },
    {
      key: "7",
      title: "Template 7",
      alias: "Template G",
      type: "Type 7",
      statut: "Disabled",
      account: "Account 7",
    },
    {
      key: "8",
      title: "Template 8",
      alias: "Template H",
      type: "Type 8",
      statut: "Enabled",
      account: "Account 8",
    },
    {
      key: "9",
      title: "Template 9",
      alias: "Template I",
      type: "Type 9",
      statut: "Disabled",
      account: "Account 9",
    },
    {
      key: "10",
      title: "Template 10",
      alias: "Template J",
      type: "Type 10",
      statut: "Enabled",
      account: "Account 10",
    },
    {
      key: "11",
      title: "Template 11",
      alias: "Template K",
      type: "Type 11",
      statut: "Enabled",
      account: "Account 11",
    },
    {
      key: "12",
      title: "Template 12",
      alias: "Template L",
      type: "Type 12",
      statut: "Disabled",
      account: "Account 12",
    },
    {
      key: "13",
      title: "Template 13",
      alias: "Template M",
      type: "Type 13",
      statut: "Enabled",
      account: "Account 13",
    },
    {
      key: "14",
      title: "Template 14",
      alias: "Template N",
      type: "Type 14",
      statut: "Enabled",
      account: "Account 14",
    },
    {
      key: "15",
      title: "Template 15",
      alias: "Template O",
      type: "Type 15",
      statut: "Disabled",
      account: "Account 15",
    },
    {
      key: "16",
      title: "Template 16",
      alias: "Template P",
      type: "Type 16",
      statut: "Enabled",
      account: "Account 16",
    },
    {
      key: "17",
      title: "Template 17",
      alias: "Template Q",
      type: "Type 17",
      statut: "Enabled",
      account: "Account 17",
    },
    {
      key: "18",
      title: "Template 18",
      alias: "Template R",
      type: "Type 18",
      statut: "Disabled",
      account: "Account 18",
    },
    {
      key: "19",
      title: "Template 19",
      alias: "Template S",
      type: "Type 19",
      statut: "Enabled",
      account: "Account 19",
    },
    {
      key: "20",
      title: "Template 20",
      alias: "Template T",
      type: "Type 20",
      statut: "Disabled",
      account: "Account 20",
    },
  ];
