export const rows = [
    {
      key: "1",
      id: "001",
      name: "United States",
      slogan: "Land of Opportunity",
      shipping: "Yes",
      tags: "Technology, Finance, Entertainment",
    },
    {
      key: "2",
      id: "002",
      name: "Canada",
      slogan: "The Great White North",
      shipping: "No",
      tags: "Natural Resources, Healthcare, Tourism",
    },
    {
      key: "3",
      id: "003",
      name: "Japan",
      slogan: "Land of the Rising Sun",
      shipping: "Yes",
      tags: "Technology, Robotics, Culture",
    },
    {
      key: "4",
      id: "004",
      name: "Germany",
      slogan: "Engineering Excellence",
      shipping: "Yes",
      tags: "Automotive, Engineering, Beer",
    },
    {
      key: "5",
      id: "005",
      name: "Brazil",
      slogan: "Order and Progress",
      shipping: "No",
      tags: "Agriculture, Football, Carnival",
    },
    {
      key: "6",
      id: "006",
      name: "Australia",
      slogan: "Down Under",
      shipping: "Yes",
      tags: "Tourism, Mining, Beaches",
    },
    {
      key: "7",
      id: "007",
      name: "India",
      slogan: "Unity in Diversity",
      shipping: "Yes",
      tags: "Technology, Agriculture, Bollywood",
    },
    {
      key: "8",
      id: "008",
      name: "China",
      slogan: "The Middle Kingdom",
      shipping: "No",
      tags: "Manufacturing, Technology, Silk Road",
    },
    {
      key: "9",
      id: "009",
      name: "France",
      slogan: "Liberty, Equality, Fraternity",
      shipping: "Yes",
      tags: "Fashion, Wine, Art",
    },
    {
      key: "10",
      id: "010",
      name: "Italy",
      slogan: "Land of Art and History",
      shipping: "No",
      tags: "Cuisine, Fashion, Art",
    },
    {
      key: "11",
      id: "011",
      name: "United Kingdom",
      slogan: "Rule Britannia",
      shipping: "Yes",
      tags: "Finance, Culture, Monarchy",
    },
    {
      key: "12",
      id: "012",
      name: "South Korea",
      slogan: "Dynamic Korea",
      shipping: "Yes",
      tags: "Technology, Pop Culture, Innovation",
    },
    {
      key: "14",
      id: "014",
      name: "Russia",
      slogan: "Mother Russia",
      shipping: "Yes",
      tags: "Energy, Space Exploration, Culture",
    },
    {
      key: "15",
      id: "015",
      name: "South Africa",
      slogan: "Rainbow Nation",
      shipping: "No",
      tags: "Wildlife, Mining, Culture",
    },
    {
      key: "16",
      id: "016",
      name: "Argentina",
      slogan: "Land of Silver",
      shipping: "Yes",
      tags: "Football, Wine, Culture",
    },
    {
      key: "17",
      id: "017",
      name: "Saudi Arabia",
      slogan: "Heart of the Islamic World",
      shipping: "Yes",
      tags: "Oil, Religion, Desert",
    },
    {
      key: "18",
      id: "018",
      name: "Turkey",
      slogan: "Bridge of Civilizations",
      shipping: "Yes",
      tags: "Cuisine, History, Tourism",
    },
    {
      key: "19",
      id: "019",
      name: "Netherlands",
      slogan: "Land of Windmills",
      shipping: "No",
      tags: "Tulips, Bicycles, Canals",
    },
    {
      key: "20",
      id: "020",
      name: "Switzerland",
      slogan: "Land of Alps",
      shipping: "Yes",
      tags: "Banking, Watches, Chocolate",
    },
];
