export const rows = [
    {
      key: "1",
      id: "1",
      partner: "Partner A",
      name: "Seller One",
      store: "Store A",
      phone: "123-456-7890",
      subscriptions: "Basic",
      statut: "Delivery Again",
      billing: "$1200",
    },
    {
      key: "2",
      id: "2",
      partner: "Partner B",
      name: "Seller Two",
      store: "Store B",
      phone: "098-765-4321",
      subscriptions: "Premium",
      statut: "Delivery Again",
      billing: "$1800",
    },
    {
      key: "3",
      id: "3",
      partner: "Partner C",
      name: "Seller Three",
      store: "Store C",
      phone: "321-654-0987",
      subscriptions: "Standard",
      statut: "Delivery Again",
      billing: "$900",
    },
    {
      key: "4",
      id: "4",
      partner: "Partner D",
      name: "Seller Four",
      store: "Store D",
      phone: "456-123-7890",
      subscriptions: "Basic",
      statut: "Delivery Again",
      billing: "$750",
    },
    {
      key: "5",
      id: "5",
      partner: "Partner E",
      name: "Seller Five",
      store: "Store E",
      phone: "789-012-3456",
      subscriptions: "Premium",
      statut: "Delivery Again",
      billing: "$1500",
    },
    {
      key: "6",
      id: "6",
      partner: "Partner F",
      name: "Seller Six",
      store: "Store F",
      phone: "147-258-3690",
      subscriptions: "Basic",
      statut: "Delivery Again",
      billing: "$400",
    },
    {
      key: "7",
      id: "7",
      partner: "Partner G",
      name: "Seller Seven",
      store: "Store G",
      phone: "258-147-3690",
      subscriptions: "Standard",
      statut: "Delivery Again",
      billing: "$980",
    },
    {
      key: "8",
      id: "8",
      partner: "Partner H",
      name: "Seller Eight",
      store: "Store H",
      phone: "369-258-1470",
      subscriptions: "Premium",
      statut: "Delivery Again",
      billing: "$2100",
    },
    {
      key: "9",
      id: "9",
      partner: "Partner I",
      name: "Seller Nine",
      store: "Store I",
      phone: "789-654-3210",
      subscriptions: "Basic",
      statut: "Delivery Again",
      billing: "$650",
    },
    {
      key: "10",
      id: "10",
      partner: "Partner J",
      name: "Seller Ten",
      store: "Store J",
      phone: "123-321-4567",
      subscriptions: "Standard",
      statut: "Delivery Again",
      billing: "$1000",
    },
    {
      key: "11",
      id: "11",
      partner: "Partner K",
      name: "Seller Eleven",
      store: "Store K",
      phone: "321-789-6540",
      subscriptions: "Basic",
      statut: "Delivery Again",
      billing: "$550",
    },
    {
      key: "12",
      id: "12",
      partner: "Partner L",
      name: "Seller Twelve",
      store: "Store L",
      phone: "654-123-0987",
      subscriptions: "Premium",
      statut: "Delivery Again",
      billing: "$2400",
    },
    {
      key: "13",
      id: "13",
      partner: "Partner M",
      name: "Seller Thirteen",
      store: "Store M",
      phone: "987-654-3214",
      subscriptions: "Standard",
      statut: "Delivery Again",
      billing: "$1120",
    },
    {
      key: "14",
      id: "14",
      partner: "Partner N",
      name: "Seller Fourteen",
      store: "Store N",
      phone: "456-789-1234",
      subscriptions: "Basic",
      statut: "Delivery Again",
      billing: "$720",
    },
    {
      key: "15",
      id: "15",
      partner: "Partner O",
      name: "Seller Fifteen",
      store: "Store O",
      phone: "147-852-9637",
      subscriptions: "Premium",
      statut: "Delivery Again",
      billing: "$1950",
    },
    // Add more rows as needed
];
