// src/core/utils/data3.js (or the appropriate path)
export const rows = [
    {
      key: "1",
      invoiceNumber: "INV-58168",
      seller: "Store A",
      date: "09/08/2024 - 19:01",
      product: "Product Alpha",
      type: "Type 1",
      qty: 50,
      totalCharges: "$100",
      soCost: "$70",
      soMargin: "$30",
      shCost: "$50",
      shMargin: "$50",
      statut: "Pending",
      paymentStatut: "Unpaid",
      options: "", // Typically handled via UI actions
      verified: true,
      status: "active",
    },
    {
      key: "2",
      invoiceNumber: "INV-58169",
      seller: "Store B",
      date: "10/08/2024 - 13:45",
      product: "Product Beta",
      type: "Type 2",
      qty: 100,
      totalCharges: "$150",
      soCost: "$105",
      soMargin: "$45",
      shCost: "$75",
      shMargin: "$75",
      statut: "Pending",
      paymentStatut: "Unpaid",
      options: "",
      verified: false,
      status: "archived",
    },
    {
      key: "3",
      invoiceNumber: "INV-58170",
      seller: "Store C",
      date: "11/08/2024 - 11:30",
      product: "Product Gamma",
      type: "Type 1",
      qty: 75,
      totalCharges: "$150",
      soCost: "$105",
      soMargin: "$45",
      shCost: "$75",
      shMargin: "$75",
      statut: "Pending",
      paymentStatut: "Unpaid",
      options: "",
      verified: true,
      status: "active",
    },
    // ... Continue for all existing rows
    {
      key: "4",
      invoiceNumber: "INV-58171",
      seller: "Store D",
      date: "12/08/2024 - 09:50",
      product: "Product Delta",
      type: "Type 3",
      qty: 120,
      totalCharges: "$200",
      soCost: "$140",
      soMargin: "$60",
      shCost: "$100",
      shMargin: "$100",
      statut: "Pending",
      paymentStatut: "Unpaid",
      options: "",
      verified: false,
      status: "archived",
    },
    // ... Continue adding the remaining rows with all fields
    {
      key: "5",
      invoiceNumber: "INV-58172",
      seller: "Store E",
      date: "13/08/2024 - 16:05",
      product: "Product Epsilon",
      type: "Type 2",
      qty: 90,
      totalCharges: "$100",
      soCost: "$70",
      soMargin: "$30",
      shCost: "$50",
      shMargin: "$50",
      statut: "Pending",
      paymentStatut: "Unpaid",
      options: "",
      verified: true,
      status: "active",
    },
    // Continue adding rows up to key "20" with all fields
    {
      key: "20",
      invoiceNumber: "INV-58187",
      seller: "Store T",
      date: "28/08/2024 - 11:00",
      product: "Product Theta",
      type: "Type 3",
      qty: 110,
      totalCharges: "$100",
      soCost: "$70",
      soMargin: "$30",
      shCost: "$50",
      shMargin: "$50",
      statut: "Pending",
      paymentStatut: "Unpaid",
      options: "",
      verified: true,
      status: "archived",
    },
  ];
  